components/usb/esp_msc_ota/test_apps:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

components/usb/usb_stream/test_apps:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

components/usb/iot_usbh/test_apps:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

components/usb/iot_usbh_cdc/test_apps:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

components/ir/ir_learn/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/knob/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/led/led_indicator/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/motor/esp_sensorless_bldc_control/test_apps/bldc_adc:
  enable:
    - if: SOC_MCPWM_SUPPORTED == 1

components/motor/esp_sensorless_bldc_control/test_apps/bldc_comparer:
  disable:
    - if: IDF_TARGET in ["esp32c2"]
components/led/lightbulb_driver/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/motor/esp_sensorless_bldc_control/test_apps/bldc_test_step_by_step:
  enable:
    - if: SOC_MCPWM_SUPPORTED == 1

components/motor/esp_simplefoc/test_apps:
  enable:
    - if: IDF_TARGET in ["esp32s3"]

components/openai/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/sensors/radar/at581x/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/display/lcd/esp_lcd_gc9b71/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/display/lcd/esp_lcd_panel_io_additions/test_apps:
  enable:
    - if: IDF_TARGET in ["esp32s3"]

components/display/lcd/esp_lcd_nv3022b/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/display/lcd/esp_lcd_sh8601/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/display/lcd/esp_lcd_spd2010/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/display/lcd/esp_lcd_st7701/test_apps:
  enable:
    - if: IDF_TARGET in ["esp32s3"]

components/display/lcd/esp_lcd_st77903_rgb:
  enable:
    - if: IDF_TARGET in ["esp32s3"]

components/display/lcd/esp_lcd_st77916/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/display/lcd/esp_lcd_st77922/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/display/lcd_touch/esp_lcd_touch_spd2010/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1

components/display/lcd_touch/esp_lcd_touch_st7123/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1
